# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(490, 550)
        font = QtGui.QFont()
        font.setPointSize(20)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 30, 101, 101))
        self.label.setMinimumSize(QtCore.QSize(70, 70))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("OCR.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.close_btn = QtWidgets.QPushButton(Form)
        self.close_btn.setGeometry(QtCore.QRect(460, 10, 20, 20))
        self.close_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.close_btn.setStyleSheet("border:none;")
        self.close_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/login-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon)
        self.close_btn.setObjectName("close_btn")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 140, 100, 50))
        self.label_2.setMinimumSize(QtCore.QSize(100, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("image/login_logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(50, 240, 400, 40))
        self.lineEdit.setMinimumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{border:1px solid gray;border-radius:16px;}")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 300, 400, 40))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{border:1px solid gray;border-radius:16px;}")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 360, 400, 40))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{border:1px solid gray;border-radius:16px;}")
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setCursorPosition(0)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setClearButtonEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.warning = QtWidgets.QLabel(Form)
        self.warning.setGeometry(QtCore.QRect(50, 410, 400, 35))
        self.warning.setMinimumSize(QtCore.QSize(400, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.warning.setFont(font)
        self.warning.setStyleSheet("color:red;")
        self.warning.setText("")
        self.warning.setAlignment(QtCore.Qt.AlignCenter)
        self.warning.setObjectName("warning")
        self.login_btn = QtWidgets.QPushButton(Form)
        self.login_btn.setGeometry(QtCore.QRect(50, 450, 400, 40))
        self.login_btn.setMinimumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("QPushButton{border:1px solid red;border-radius:16px;color:white;background-color:red;}")
        self.login_btn.setObjectName("login_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入APPID"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "请输入SecretID"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "请输入SecretKey"))
        self.login_btn.setText(_translate("Form", "登    录"))

